# Generated by wallust — consumed by ~/.config/scripts/niri/wallust_niri_colors.sh
# Do not read ~/.cache/wallust/sequences instead: the wallpaper picker runs
# `wallust run -qs`, and -s skips writing that file, so it goes stale.
NIRI_BORDER_FROM="{{color4}}"
NIRI_BORDER_TO="{{color6}}"
