# $location = ~/Pictures/andrew-ruiz-RbIQ3YvUREw-unsplash.jpg
# preload = $location
# wallpaper = eDP-1,$location
# wallpaper = HDMI-A-1,$location
splash = false

wallpaper {
    monitor =
    # path = ~/Pictures/andrew-ruiz-RbIQ3YvUREw-unsplash.jpg
    path = ~/Pictures/ryunosuke-kikuno-VXp-9HwN1eg-unsplash.jpg
    fit_mode = cover
}
